[project]
name = "mp4_2_mp3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "moviepy>=2.2.1",
    "flask>=3.0.2",
    "openai>=2.6.0",
    "requests>=2.32.5",
]
